# This workflow will build a docker container, publish it to Github Packages
name: Build DEV

on:
  push:
    branches: [main-deployment]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: S3 and CloudFront Deploy
        uses: lbertenasco/s3-deploy@v1.2.4
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
